apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/samaddico/hostaway-devops-task.git
    targetRevision: main
    path: helm
    helm:
      valueFiles:
        - ../argocd/dev/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
