replicaCount: 1

image:
  repository: ghcr.io/samaddico/nginx-app
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: 0118e2c0e310368f0103671de03e4a572db6f5e1

nameOverride: "nginx-app"
fullnameOverride: ""


service:
  type: NodePort
  targetPort: 80
  port: 80
  nodePort: 30080

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

